### ISSUE TITLE
Shelly device ID must be uppercase in automation config to be configured with device class etc.

### ISSUE THREAD

**Issue by brnstd-dev** [bieniu/home-assistant-config#10]
All of my Shelly devices are uppercase, when I inspect them in HA

![image](https://user-images.githubusercontent.com/65893730/175531410-a3b828b0-dfd7-42fb-8364-160f904f2277.png)

However, I grabbed the device ID from the states in dev tools, where they are presented in lowercase, and as a result did not get a "cover" entity

![image](https://user-images.githubusercontent.com/65893730/175531473-4dc0dc99-d3f9-43d3-8aa9-adc383eac3c9.png)

At least, I believe this should be added to the "troubleshooting" section. Or maybe this could be my first open source PR? :-)

**Comment by bieniu** [comment]
I think you opened this issue in wrong repository.
