### ISSUE TITLE
notification_dead_or_unavailable

### ISSUE THREAD

**Issue by gromar88** [bieniu/home-assistant-config#11]
Hello,

I have problem with Notification of dead or unavaible enteties in automation.yaml - other notifications work splendid. This one generating warning in logger- I don't know exactly what's the problem:

`` Template variable warning: 'ignored' is undefined when rendering '{% macro dead_unavailable_entities() %} {% for domain in domains %} {% for room in rooms %} {% for item in states[domain] if (room in item.entity_id or 'node' in item.entity_id) and not (item.entity_id in ignored or 'battery' in item.entity_id or 'status' in item.entity_id) and item.state is defined and item.state in reported_states %} {{ item.entity_id }} {% endfor %} {% endfor %} {% endfor %} {% endmacro %} {{ dead_unavailable_entities() | trim != "" }}'
Template variable warning: 'ignored' is undefined when rendering '{% macro dead_unavailable_entities() %}{% for domain in domains %}{% for room in rooms %}{% for item in states[domain] if (room in item.entity_id or 'node' in item.entity_id) and not (item.entity_id in ignored or 'battery' in item.entity_id or 'status' in item.entity_id) and item.state is defined and item.state in reported_states %}{% if device_attr(item.entity_id, 'name_by_user') %}{{ device_attr(item.entity_id, 'name_by_user') }}{% if area_name(item.entity_id) %}, {{ area_name(item.entity_id) }}{% endif %}|{% else %}{{ item.name }}{% if area_name(item.entity_id) %}, {{ area_name(item.entity_id) }}{% endif %} ({{ item.entity_id }})|{% endif %}{% endfor %}{% endfor %}{% endfor %}{% endmacro %}{% set entities = dead_unavailable_entities().split('|') | unique | list %} Następujące urządzenia/encje mają nieprawidłowe stany: {% for entity in entities %}{% if entity %}<br> - {{ entity }}{% endif %}{% endfor %}' ``

Thank you in advance for any info and help :)

**Comment by bieniu** [comment]
And the warning says...

**Comment by gromar88** [comment]
I somehow missed 'ignored' variable in notification - thanks for comment :)
