### ISSUE TITLE
heating_thermostat_update.py and HomeKit

### ISSUE THREAD

**Issue by kamkilt** [bieniu/home-assistant-config#4]
Hi, first I would like to thanks to You, great work, I found a lot of nice ideas in your config.

I found issue and changed little bit your script to add better compatibility with HomeKit, from config I can see that You're also using HomeKit.

First, I had a bug that temperature which was correctly displayed in home assistant GUI wasn't displayed in HomeKit devices (still 21 -  default temp if is not known for HomeKit component), in logs temperature was sent but not shown in HomeKit, after adding additional float() it was displayed correctly in HomeKit:

`temp = float(hass.states.get(sensor_id).state)`

Also I added operation_mode attribute, which I found that HomeKit uses for showing state of thermostat, when sending this attribute, HomeKit is showing heat or off status, which is very nice.
Operation mode works only in one way from home assistant > HomeKit, changing mode in HomeKit doesn't do anything. 
 
my code below:

```
if thermostat_id and sensor_id:
    # added float()
    temp = float(hass.states.get(sensor_id).state)
    if temp and temp != 'unknown':
        thermostat = hass.states.get(thermostat_id)
        attributes = thermostat.attributes.copy()
        attributes['current_temperature'] = temp
        # additional attribute, not sure is it needed
        attributes['operation_list'] = "heat,off"
        if float(attributes['temperature']) > idle_heat_temp:
            state = heat_state
            # additional attribute
            attributes['operation_mode'] = "heat"
        else:
            state = idle_state
            # additional attribute
            attributes['operation_mode'] = "off"
        hass.states.set(thermostat_id, state, attributes)
else:
    logger.error("Wrong arguments!")
```

**Comment by bieniu** [comment]
@kamkilt Nice catch. Thanks. The script has been updated. I made the operation_mode and operation_list dependent on heat_state and idle_state.

**Comment by kamkilt** [comment]
For working with HomeKit it should be hardcoded names, HomeKit only interprets: off, heat, cool operation mode, even letter case is important.

**Comment by bieniu** [comment]
Do you think that it is a good idea that the states would be different in Home Assistant and HomeKit? Currently, the default states are 'heat' and 'off'. If someone changes the state description, then it will lose compatibility with HomeKit.

**Comment by kamkilt** [comment]
In my opinion "operation_mode" should be hard coded, it is not shown in GUI, only name used in communication and status showing, also in generic_thermostat it is also not changeable name.

So if some one wants to change display name attribute "state" to local language, "operation_mode" will be intact and work with HomeKit.

In HomeKit "operation_mode" is also translated depending of language of system.

But it can be user decision, I saw You added a comment about this.
