### ISSUE TITLE
HACS integration

### ISSUE THREAD

**Issue by fsteccanella** [bieniu/home-assistant-config#8]
Hi,
first of all thanks for your [shellies_discovery](https://github.com/bieniu/home-assistant-config/blob/master/python_scripts/shellies_discovery.py) script!

On my hass instance I have switched from custom_updater to HACS (https://github.com/custom-components/hacs) and I would like to keep track of your script using it, but the primary requirement for doing so is that each repository contains one and only one element.

Do you think that you could extract your script to it's own repository?

Ref:
HACS python_scripts feature request: https://github.com/custom-components/hacs/issues/113
HACS sample python_scripts repo: https://github.com/ludeeus/ps-hacs

Thanks in advance

**Comment by bieniu** [comment]
Script is available in HACS since few days https://github.com/bieniu/ha-shellies-discovery

**Comment by fsteccanella** [comment]
Fantastic .. I had not noticed!

Thanks!
